/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedMonthlyGoalsRouteImport } from './routes/_authenticated/monthly-goals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonthlyGoalsRoute =
  AuthenticatedMonthlyGoalsRouteImport.update({
    id: '/monthly-goals',
    path: '/monthly-goals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/monthly-goals': typeof AuthenticatedMonthlyGoalsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/monthly-goals': typeof AuthenticatedMonthlyGoalsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/monthly-goals': typeof AuthenticatedMonthlyGoalsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/achievements'
    | '/applications'
    | '/history'
    | '/learning'
    | '/monthly-goals'
    | '/profile'
    | '/projects'
    | '/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/achievements'
    | '/applications'
    | '/history'
    | '/learning'
    | '/monthly-goals'
    | '/profile'
    | '/projects'
    | '/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/_authenticated/achievements'
    | '/_authenticated/applications'
    | '/_authenticated/history'
    | '/_authenticated/learning'
    | '/_authenticated/monthly-goals'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monthly-goals': {
      id: '/_authenticated/monthly-goals'
      path: '/monthly-goals'
      fullPath: '/monthly-goals'
      preLoaderRoute: typeof AuthenticatedMonthlyGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedMonthlyGoalsRoute: typeof AuthenticatedMonthlyGoalsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedMonthlyGoalsRoute: AuthenticatedMonthlyGoalsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
