ALTER TABLE public.profiles
  ALTER COLUMN name DROP NOT NULL,
  ALTER COLUMN college DROP NOT NULL,
  ALTER COLUMN passout_year DROP NOT NULL,
  ALTER COLUMN goal DROP NOT NULL,
  ALTER COLUMN tagline DROP NOT NULL,
  ALTER COLUMN passion DROP NOT NULL,
  ALTER COLUMN dream DROP NOT NULL,
  ALTER COLUMN date_of_birth DROP NOT NULL;